name: databricksNotebookDeploy
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Databricks CLI
      uses: microsoft/install-databricks-cli@v1.0.0
    - name: Clean Databricks Path
      continue-on-error: true
      shell: pwsh
      run: |-
        $tokenFile = "${{ runner.temp }}/tokenfile.txt"
        echo ${{ secrets.DATABRICKS_TOKEN }} > $tokenFile
        databricks configure --host "https://westus2.azuredatabricks.net" --token-file $tokenFile
        rm -f $tokenFile
        databricks workspace delete --recursive "/Shared/UploadedNotebooks"
    - name: Databricks Notebooks deployment
      uses: microsoft/databricks-import-notebook@v1.0.0
      with:
        databricks-host: https://westus2.azuredatabricks.net
        databricks-token: "${{ secrets.DATABRICKS_TOKEN }}"
        local-path: Databricks/Notebooks
        remote-path: "/Shared/UploadedNotebooks"
