name: databricksNotebookDeploy
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0
    
    - name: Delete workspace
      run: |-
        databricks configure -h
        databricks configure -t <<< https://westus2.azuredatabricks.net
    
    - name: databricks-import-directory
      uses: microsoft/databricks-import-notebook@v1.0.0
      with:
        databricks-host: https://westus2.azuredatabricks.net
        databricks-token: "${{ secrets.DATABRICKS_TOKEN }}"
        local-path: Databricks/Notebooks
        remote-path: "/Shared/UploadedNotebooks"
   
