name: Manual Intervention
on:
  workflow_dispatch:
jobs:
  Stage-1-job-1:
    runs-on: windows-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    steps:
    - name: PowerShell Script
      run: |-
        # Write your PowerShell commands here.
        Write-Host "Before Intervention"
      shell: powershell
  Stage-1-job-2:
    needs:
    - Stage-1-job-1
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    environment:
      name: approval_required
  Stage-1-job-3:
    needs:
    - Stage-1-job-2
    runs-on: windows-latest
    concurrency:
      group: "${{ github.ref }}"
      cancel-in-progress: false
    if: github.event_type != 'pull_request'
    steps:
    - name: PowerShell Script
      run: |-
        # Write your PowerShell commands here.
        Write-Host "After Intervention"
      shell: powershell
