name: PowerShellTest
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  Job_1:
    name: Agent job 1
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run PowerShell
      uses: azure/powershell@v1
      with:
        inlineScript: |
          echo "HelloWorld"
        azPSVersion: 'latest'
