name: Tokenization
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Print file pre-tokenization
      run: cat 'tokenization/folder1/folder2/fileWithToken.txt'
    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: __
        tokenSuffix: __
        files: '[tokenization/*1/folder*/**/**/fileWithToken1.txt,tokenization/*1/folder*/**/**/fileWithToken2.txt]'
      env:
        TOKEN1: "New Value"
    - name: Print file post-tokenization
      run: cat 'tokenization/folder1/folder2/fileWithToken.txt'
   
