name: Tokenization
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '{'
        tokenSuffix: '}'
        files: 'tokenization/folder1/folder2/fileWithToken.txt'
      env:
        TOKEN1: "New Value"
      
   
