name: XamarinAndroidTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print env values
      run: |- 
        echo "Runner OS - $ENV:RUNNER_OS"
        echo "Run Id - $ENV:GITHUB_RUN_ID"
        
    - name: script Test
      id: set-result
      uses: actions/github-script@v4
      with:
        script: |-
          const globber = await glob.create("**/*.csproj")
          for await (const file of globber.globGenerator()) {
            await exec.exec(`echo ${file}`)
          }
          
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
          
    - name: Set default Xamarin SDK versions
      if: RUNNER.OS == 'macOS'
      run: |-
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.4 --android=10.2
        cat $VM_ASSETS/select-xamarin-sdk-v2.sh
        echo 'Library'; ls '/Library'
        echo 'Library/Java...'; ls '/Library/Java/'
        echo 'Library/Frameworks...'; ls '/Library/Frameworks/'
        echo 'Users/runner/hostedtoolcache/'; ls '/Users/runner/hostedtoolcache/'
        msbuild -ver
      
    - name: get dirs
      run: |-
        echo $env:JAVA_HOME
        
    - name: Uses MsBuild
      if: ${{ RUNNER.OS == 'Windows' }}
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-version: '15.0'
      
    - name: Install dependencies
      run: nuget restore "XamarinAndroid/FingerPaint/FingerPaint.sln"
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        architecture: x64
        
    - name: Run build
      run: |- 
        echo "${{ env.JHOME }}"
        echo $Env:JHOME
        msbuild "XamarinAndroid/FingerPaint/FingerPaint/FingerPaint.csproj" /t:PackageForAndroid /p:Configuration=Debug /p:JavaSdkDirectory="${{ env.JAVA_HOME }}"
