name: XamarinAndroidTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print env values
      run: |- 
        echo "Runner OS - $ENV:RUNNER_OS"
        echo "Run Id - ENV:GITHUB_RUN_ID"
      
    - name: Uses MsBuild
      if: ${{ RUNNER_OS == 'Windows' }}
      uses: microsoft/setup-msbuild@v1.0.3
      
    - name: Install dependencies
      run: nuget restore "XamarinAndroid/FingerPaint/FingerPaint.sln"

    - name: Build
      run: msbuild "XamarinAndroid/FingerPaint/FingerPaint/FingerPaint.csproj" /t:PackageForAndroid /p:Configuration=Debug
