name: XamarinAndroidTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: nuget restore "XamarinAndroid/FingerPaint/FingerPaint.sln"
    - name: Uses MsBuild
      if: runner.os == 'windows'
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-version: '15.0'
    - name: Install Java Version 8
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '1.8'
    - name: Build Xamarin Project
      uses: actions/github-script@v4
      with:
        script: |-
          const globber = await glob.create("**/*.csproj")
          for await (const file of globber.globGenerator()) {
            exec.exec(`msbuild "${file}" /p:Configuration=Debug /t:PackageForAndroid /t:clean /p:verbosity=quiet /p:JavaSdkDirectory="${{ env.JAVA_HOME }}"`)
          }
