name: XamarinAndroidTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print env values
      run: |- 
        echo "Runner OS - $ENV:RUNNER_OS"
        echo "Run Id - $ENV:GITHUB_RUN_ID"
        
    - name: Set default Xamarin SDK versions
      if: RUNNER.OS == 'macOS'
      run: |-
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.4 --android=10.2
        cat $VM_ASSETS/select-xamarin-sdk-v2.sh
        echo 'Library'; ls '/Library'
        echo 'Library/Java...'; ls '/Library/Java/'
        echo 'Library/Frameworks...'; ls '/Library/Frameworks/'
        echo 'Users/runner/hostedtoolcache/'; ls '/Users/runner/hostedtoolcache/'
        msbuild -ver
      
    - name: get dirs
      run: |-
        ls 'C:\Program Files\Android\jdk\'
        ls $env:RUNNER_TOOL_CACHE\Java_Adopt_jdk
        echo %JAVA_HOME%
        
    - name: Uses MsBuild
      if: ${{ RUNNER.OS == 'Windows' }}
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-version: '15.0'
      
    - name: Install dependencies
      run: nuget restore "XamarinAndroid/FingerPaint/FingerPaint.sln"
      
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        architecture: x86
    - run: |- 
        echo %JAVA_HOME%
        msbuild "XamarinAndroid/FingerPaint/FingerPaint/FingerPaint.csproj" /t:PackageForAndroid /p:Configuration=Debug
