name: XamarinAndroidTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print runner OS
      run: echo "Runner OS - $RUNNER_OS"
      
    - name: Set default Xamarin SDK versions
      if: env.RUNNER_OS == 'macOS'
      run: |-
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2
        type $VM_ASSETS/select-xamarin-sdk-v2.sh

    - name: Uses MsBuild
      if: env.RUNNER_OS == 'Windows'
      uses: microsoft/setup-msbuild@v1.0.3
      
    - name: Setup .NET Core SDK 5.0.x
      if: env.RUNNER_OS == 'foo'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore "XamarinAndroid/FingerPaint/FingerPaint.sln"

    - name: Build
      run: msbuild "XamarinAndroid/FingerPaint/FingerPaint/FingerPaint.csproj" /t:PackageForAndroid /p:Configuration=Debug
