name: XamarinAndroidTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print env values
      run: |- 
        echo "Runner OS - $ENV:RUNNER_OS"
        echo "Run Id - $ENV:GITHUB_RUN_ID"
        
    - name: Set default Xamarin SDK versions
      if: RUNNER.OS == 'macOS'
      run: |-
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=10.2
        cat $VM_ASSETS/select-xamarin-sdk-v2.sh
        ls '/Library/Frameworks/'
        ls '/Library/Frameworks/Mono.framework/'
        ls '/Library/Frameworks/Mono.framework/Versions/'
      
    - name: Uses MsBuild
      if: ${{ RUNNER.OS == 'Windows' }}
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-version: '15.0'
      
    - name: Install dependencies
      run: nuget restore "XamarinAndroid/FingerPaint/FingerPaint.sln"

    - name: Build
      run: msbuild "XamarinAndroid/FingerPaint/FingerPaint/FingerPaint.csproj" /t:PackageForAndroid /p:Configuration=Debug
