name: XamarinAndroidTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: nuget restore "XamarinAndroid/FingerPaint/FingerPaint.sln"
    - name: Uses MsBuild
      if: runner.os == 'windows'
      uses: microsoft/setup-msbuild@v1.0.3
      with:
        vs-version: '15.0'
    - name: Install Java Version 8
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 'default'
    - name: Build Xamarin Project
      run: msbuild ${{ env.PROJECT_PATH }} /p:Configuration=Debug /t:PackageForAndroid /t:clean /p:verbosity=quiet /p:JavaSdkDirectory="${{ env.JAVA_HOME }}"
      env:
        PROJECT_PATH: XamarinAndroid\FingerPaint\FingerPaint\FingerPaint.csproj
