name: YarnInstallerTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  serverjob:
    runs-on: ubuntu-latest
    steps:
    - name: YarnInstaller
      run: npm install -g yarn@>1.20.x
    - name: YarnVersion
      run: |-
        yarn version
