name: YarnInstallerTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  serverjob:
    runs-on: ubuntu-latest
    steps:
    - name: YarnInstaller 15
      run: yarn set version 1.15.*
    - name: YarnInstaller 16
      run: yarn set version 1.16.*
    - name: YarnInstaller 17
      run: yarn set version 1.17.*
