name: YarnInstallerTesting
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  SYSTEM.DEBUG: 'false'
jobs:
  Job_1:
    name: Agent job 1
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Yarn 1.22.x
      run: npm install yarn@"1.22.x"
    - name: Use Yarn with default value
      run: npm install yarn@"1.x"
